version: '3.5'

services:

   developer:
      networks:
         - kafka
      entrypoint: /bin/bash
      command:  -c "sleep infinity"
      build:
         context: .
         dockerfile: Dockerfile
         args:
         - USERNAME=dev
         target: developer
      command:  -c "/Project/build/consumer" 
      environment:
         KAFKAURL: "redpanda:29092" 
         KAFKATOPIC: "test"
   redpanda:
      entrypoint: /bin/sh
      command: -c "/start.sh"
      volumes: 
         - ./start.sh:/start.sh
      
      # NOTE: Please use the latest version from github
      image: docker.vectorized.io/vectorized/redpanda:v21.7.6
      container_name: redpanda-1
      ports:
      - 9092:9092
      - 29092:29092
      networks:
         - kafka

networks:
   kafka:
      name: kafka

